// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// compute_regularized_path_cpp
void compute_regularized_path_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::List numerical_condition, Rcpp::List goodness_of_fit, Rcpp::List coefficient);
RcppExport SEXP _lslx_compute_regularized_path_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP numerical_conditionSEXP, SEXP goodness_of_fitSEXP, SEXP coefficientSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type numerical_condition(numerical_conditionSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type goodness_of_fit(goodness_of_fitSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type coefficient(coefficientSEXP);
    compute_regularized_path_cpp(reduced_data, reduced_model, control, numerical_condition, goodness_of_fit, coefficient);
    return R_NilValue;
END_RCPP
}
// compute_coefficient_matrice_cpp
Rcpp::List compute_coefficient_matrice_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::NumericVector theta_value);
RcppExport SEXP _lslx_compute_coefficient_matrice_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP theta_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_value(theta_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_coefficient_matrice_cpp(reduced_data, reduced_model, control, theta_value));
    return rcpp_result_gen;
END_RCPP
}
// compute_implied_cov_cpp
Rcpp::List compute_implied_cov_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::NumericVector theta_value);
RcppExport SEXP _lslx_compute_implied_cov_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP theta_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_value(theta_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_implied_cov_cpp(reduced_data, reduced_model, control, theta_value));
    return rcpp_result_gen;
END_RCPP
}
// compute_implied_mean_cpp
Rcpp::List compute_implied_mean_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::NumericVector theta_value);
RcppExport SEXP _lslx_compute_implied_mean_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP theta_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_value(theta_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_implied_mean_cpp(reduced_data, reduced_model, control, theta_value));
    return rcpp_result_gen;
END_RCPP
}
// compute_moment_gradient_cpp
Rcpp::NumericMatrix compute_moment_gradient_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::NumericVector theta_value);
RcppExport SEXP _lslx_compute_moment_gradient_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP theta_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_value(theta_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_moment_gradient_cpp(reduced_data, reduced_model, control, theta_value));
    return rcpp_result_gen;
END_RCPP
}
// compute_expected_fisher_information_cpp
Rcpp::NumericMatrix compute_expected_fisher_information_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::NumericVector theta_value);
RcppExport SEXP _lslx_compute_expected_fisher_information_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP theta_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_value(theta_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_expected_fisher_information_cpp(reduced_data, reduced_model, control, theta_value));
    return rcpp_result_gen;
END_RCPP
}
// compute_loss_gradient_cpp
Rcpp::NumericMatrix compute_loss_gradient_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::NumericVector theta_value);
RcppExport SEXP _lslx_compute_loss_gradient_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP theta_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_value(theta_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_loss_gradient_cpp(reduced_data, reduced_model, control, theta_value));
    return rcpp_result_gen;
END_RCPP
}
// compute_regularizer_gradient_cpp
Rcpp::NumericMatrix compute_regularizer_gradient_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::NumericVector theta_value, double lambda, double gamma);
RcppExport SEXP _lslx_compute_regularizer_gradient_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP theta_valueSEXP, SEXP lambdaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_value(theta_valueSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_regularizer_gradient_cpp(reduced_data, reduced_model, control, theta_value, lambda, gamma));
    return rcpp_result_gen;
END_RCPP
}
// compute_objective_gradient_cpp
Rcpp::NumericMatrix compute_objective_gradient_cpp(Rcpp::List reduced_data, Rcpp::List reduced_model, Rcpp::List control, Rcpp::NumericVector theta_value, double lambda, double gamma);
RcppExport SEXP _lslx_compute_objective_gradient_cpp(SEXP reduced_dataSEXP, SEXP reduced_modelSEXP, SEXP controlSEXP, SEXP theta_valueSEXP, SEXP lambdaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_data(reduced_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type reduced_model(reduced_modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_value(theta_valueSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_objective_gradient_cpp(reduced_data, reduced_model, control, theta_value, lambda, gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lslx_compute_regularized_path_cpp", (DL_FUNC) &_lslx_compute_regularized_path_cpp, 6},
    {"_lslx_compute_coefficient_matrice_cpp", (DL_FUNC) &_lslx_compute_coefficient_matrice_cpp, 4},
    {"_lslx_compute_implied_cov_cpp", (DL_FUNC) &_lslx_compute_implied_cov_cpp, 4},
    {"_lslx_compute_implied_mean_cpp", (DL_FUNC) &_lslx_compute_implied_mean_cpp, 4},
    {"_lslx_compute_moment_gradient_cpp", (DL_FUNC) &_lslx_compute_moment_gradient_cpp, 4},
    {"_lslx_compute_expected_fisher_information_cpp", (DL_FUNC) &_lslx_compute_expected_fisher_information_cpp, 4},
    {"_lslx_compute_loss_gradient_cpp", (DL_FUNC) &_lslx_compute_loss_gradient_cpp, 4},
    {"_lslx_compute_regularizer_gradient_cpp", (DL_FUNC) &_lslx_compute_regularizer_gradient_cpp, 6},
    {"_lslx_compute_objective_gradient_cpp", (DL_FUNC) &_lslx_compute_objective_gradient_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_lslx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
