# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_regularized_path_cpp <- function(reduced_data, reduced_model, control, numerical_condition, goodness_of_fit, coefficient) {
    invisible(.Call('_lslx_compute_regularized_path_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, numerical_condition, goodness_of_fit, coefficient))
}

compute_coefficient_matrice_cpp <- function(reduced_data, reduced_model, control, theta_value) {
    .Call('_lslx_compute_coefficient_matrice_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, theta_value)
}

compute_implied_cov_cpp <- function(reduced_data, reduced_model, control, theta_value) {
    .Call('_lslx_compute_implied_cov_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, theta_value)
}

compute_implied_mean_cpp <- function(reduced_data, reduced_model, control, theta_value) {
    .Call('_lslx_compute_implied_mean_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, theta_value)
}

compute_moment_gradient_cpp <- function(reduced_data, reduced_model, control, theta_value) {
    .Call('_lslx_compute_moment_gradient_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, theta_value)
}

compute_expected_fisher_information_cpp <- function(reduced_data, reduced_model, control, theta_value) {
    .Call('_lslx_compute_expected_fisher_information_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, theta_value)
}

compute_loss_gradient_cpp <- function(reduced_data, reduced_model, control, theta_value) {
    .Call('_lslx_compute_loss_gradient_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, theta_value)
}

compute_regularizer_gradient_cpp <- function(reduced_data, reduced_model, control, theta_value, lambda, gamma) {
    .Call('_lslx_compute_regularizer_gradient_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, theta_value, lambda, gamma)
}

compute_objective_gradient_cpp <- function(reduced_data, reduced_model, control, theta_value, lambda, gamma) {
    .Call('_lslx_compute_objective_gradient_cpp', PACKAGE = 'lslx', reduced_data, reduced_model, control, theta_value, lambda, gamma)
}

